Feature/reporting api
spyderbat/spyctl pull request #273
Opened 2024-04-09 19:33 UTC by spyder-guy

2024-04-09 21:15 UTC, brent-spyder requested changes
Make the two environment variable changes and then I think it's good to go

2024-04-10 12:45 UTC, spyder-guy commented on spyctl_api/test-docker-compose.yaml
> +      - AWS_ROLE_ARN=arn:aws:iam::211125369423:role/OrganizationAccountAccessRole
✅

2024-04-10 12:46 UTC, spyder-guy commented on spyctl_api/test-docker-compose.yaml
> +      - REPORT_BUCKET=integration2.reports
✅

2024-04-10 13:08 UTC, brent-spyder approved these changes

2024-04-18 16:42 UTC, brent-spyder requested changes

2024-04-18 16:42 UTC, brent-spyder commented on spyctl_api/app/config.py
> +def deployment_2_bucket(deployment: str) -> str:
Not the biggest fan of having the hard coded bit in the python file, but in the interest of getting the feature out I think we'll just live with it.

Could you put a TODO comment here to move this to a loadable config file? Who knows if anyone will ever stand up their own spyctl api service, but I'd like to leave the option open

2024-04-18 18:46 UTC, spyder-guy commented on spyctl_api/app/config.py
> +def deployment_2_bucket(deployment: str) -> str:
done

2024-04-18 18:50 UTC, brent-spyder approved these changes

2024-04-18 18:54 UTC, merged